# Generated by Django 4.0.3 on 2022-10-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='automobile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salesrecords', to='sales_rest.automobilevo'),
        ),
    ]
