# Generated by Django 4.0.3 on 2022-10-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesrecords', to='sales_rest.automobilevo'),
        ),
    ]
