# Generated by Django 4.0.3 on 2022-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_num',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
