# Generated by Django 4.0.3 on 2022-10-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('date', 'technician')},
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
