# Generated by Django 4.0.3 on 2022-10-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_vin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
