# Generated by Django 4.0.3 on 2022-10-25 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='manufacturer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(max_length=100)),
                ('vin_new', models.CharField(max_length=17, unique=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='service_rest.technician')),
            ],
            options={
                'ordering': ('date', 'technician'),
            },
        ),
    ]
